### ISSUE TITLE
Language to ISO 639-2 three letter codes

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#21]
According to the harvester specs, language values should be transformed to ISO 639-2 three letter codes for DPLA and for Primo.

<img width="637" alt="screen shot 2017-03-16 at 12 57 45 pm" src="https://cloud.githubusercontent.com/assets/6174191/24016135/39bc6ea6-0a48-11e7-88d1-2489767339f0.png">

Please add this transformation to the harvester.

Example records:
http://harvester-dev.orbiscascade.org/record/c242d4ae682bae4ac74fecc185d37046
http://harvester-dev.orbiscascade.org/record/fdcebb4740769c1c704e50e4634f9438

@jallibunn

**Comment by ewg118** [comment]
Okay, this has finally been implemented. I have a lookup list derived from the LC authorities, which contains the language name, three letter code, and two letter code. If the harvester encounters a dc:language that is two characters, it will attempt to resolve the three-letter code from the 2 characters. If the dc:language is three characters, it will look for a match in the lookup table, and then output `dcterms:language "{ISO 639-2 code}"` if found. Otherwise, it will try to match on the language name. It ought to be successful in nearly every case, but the preferred label for the "cre" code is "Creoles and Pidgins, English-based (Other)", so if the dc:language is "Creole", it won't score a hit for this language. I don't think this will be an issue.

For reference, here are the distinct values for dcterms:language currently in the harvester: http://bit.ly/2mUp8IR

The `<br>` tags would be replaced with a blank space in the current code, but "latin french" would still be a problem.

I did a search in the harvester SPARQL for `german<br>latin`, and it is a ContentDM instance, surprisingly (http://cdm16786.contentdm.oclc.org/cdm/ref/collection/maps/id/160). ContentDM usually separates multiple values by ';', but perhaps language is not one of those multivalue fields, so they used HTML breaks instead? How do you want to proceed? Should languages be split on ';' and `<br>`?

**Comment by ewg118** [comment]
I think bitly garbled the SPARQL query URL, try this: https://gist.github.com/ewg118/42f7e6f89f3594ebe6066773f57ee651

**Comment by adehner** [comment]
Great!

I hope when sets are actually submitted, the language values will have been cleaned up locally and so they will be more standardized than those in the look-up list! I know UW has been delimiting some fields with line breaks, but they are aware that this deviates from the Alliance Best Practices so they will probably clean these up locally before submitting in the harvester. I have seen instances of languages delimited with a comma or the word "or" in other sets. But these too should be cleaned up before actual submission.

To proceed...
Alliance members know that multiple language values should be semicolon delimited or present in separate properties. I'd like to be consistent with this recommendation. So I think we should continue to split on only ';' 

When met with values like "near omak, wa" or "latin<br>german", and the harvester doesn't score a hit, what will the harvester do?

**Comment by ewg118** [comment]
Currently, anything that doesn't normalize to a 3 letter code will be ignored and not go through to the DPLA MAP. DPLA requires language only when it's available, so I think it's best to provide them only standard codes.

**Comment by adehner** [comment]
I agree. This sounds good.
