### ISSUE TITLE
sourceResource metadata (URLs) overflowing container

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#29]
When previewing records in the "preview set" page, the thumbnail overlaps the overflowing sourceResource metadata when the sourceResource metadata is present as a long URL. The URL doesn't break and wrap neatly, instead it overflows. See the screenshot below. 

<img width="709" alt="screen shot 2017-03-28 at 2 30 37 pm" src="https://cloud.githubusercontent.com/assets/6174191/24428438/51b0a516-13c3-11e7-8493-787bce84f8e3.png">

One way to address this would be to add the css {overflow-wrap:break-word;} to one of the containers.

@jallibunn

**Comment by ewg118** [comment]
This is more of a browser-specific issue, as Firefox already wraps long URLs at the &. I changed the text alignment to right on the div that contains the images, though, so that might fix the display anyway.

![screenshot from 2017-03-29 10-58-38](https://cloud.githubusercontent.com/assets/563187/24461322/b6e9152a-146e-11e7-93d5-41c67ec8caff.png)

**Comment by adehner** [comment]
Looks good. Thanks!
