### ISSUE TITLE
Trailing punctuation is trimmed from dc:description and dc:rights

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#41]
The harvester is trimming trailing periods from dc:description and dc:rights values. Trailing punctuation should be kept for these field values.

Trimmed values are visible in the following sets:
http://digital.lib.washington.edu/dspace-oai/request?verb=ListRecords&set=col_1773_4972&metadataPrefix=oai_dc

http://content.wwu.edu/oai/oai.php?verb=ListRecords&metadataPrefix=oai_dc&set=walc 

@jallibunn

**Comment by ewg118** [comment]
As indicated by issue 42, there are instances where stripping HTML tags will result in run-in words. Currently, HTML tags are replaced with a space, and multiple whitespaces are replaced with one whitespace, which is why sometimes there is extraneous whitespace around punctuation. There's no completely consistent way in regular expressions around this problem.

**Comment by ewg118** [comment]
Actually, I meant this comment for a different issue I can't seem to find now.

**Comment by ewg118** [comment]
Trailing period is no longer stripped from description and rights.

**Comment by adehner** [comment]
Thanks, I think you're referring to issue #2
