### ISSUE TITLE
VIAF/AAT search results box: accommodate lots of results & long labels

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#45]
When a VIAF/AAT lookup returns many results (more than 10?) the count that displays above the lookup box is incorrect.

When a lookup result is a long text string, the text is clipped. Please make the lookup box larger or allow the user to expand its size to read the box's contents.

This behavior is visible when attempting to enrich "united states. Bureau of land management." in the following set: http://dc.ewu.edu/do/oai/?verb=ListRecords&metadataPrefix=simple-dublin-core&set=publication:biol_fac

<img width="489" alt="screen shot 2017-04-14 at 4 46 46 pm" src="https://cloud.githubusercontent.com/assets/6174191/25058769/fa588d2a-2131-11e7-874e-601492775cc8.png">

@jallibunn

**Comment by ewg118** [comment]
I started working on this, but have found that the VIAF search API is somewhat problematic with its results. If there are many authority headings, they will all appear within the RSS feed title, making it impossible to distinguish between the LC heading and any other. I will look at some other options from VIAF. I think it is possible to get query results back in RDF or another XML format that more clearly labels the authority file source.

**Comment by ewg118** [comment]
The RSS output from VIAF has changed considerably over the years since I originally wrote the code for the lookup in EADitor in 2011. I rewrote it so that it parses the full VIAF XML response (which includes 100 results), displaying only the Library of Congress preferred heading as the output in the select list. The LC heading is used when generating the skos:prefLabel in the edm:Agent on harvest.

**Comment by adehner** [comment]
Displaying the LC preferred heading as the output will definitely improve the results.
However, we've been telling folks that ULAN and ISNI headings would work for enrichment as well. Will the harvester enrich text strings that match ULAN or ISNI labels?

I can see that the box is wider, but it's still not wide enough to view long lookup results (see bureau of land management example). Please enable horizontal scrolling or make the box horizontally expandable, to accommodate these labels.

**Comment by ewg118** [comment]
No, it will not enrich with labels from ISNI or ULAN. Using labels from all of VIAF can be complicated as there has been minimal disambiguation (especially for ULAN), and so there are a lot of duplicates in VIAF. There are always some issues about which preferred label to display when it doesn't detect the LC heading. The GND might be the most comprehensive of all authority files because museums and the national archaeological databases contribute to it as well, so you get a lot of a people that don't get headings in any other library catalog. The ISNI preferred label is often not the same as LC, and doesn't conform to AACR2. I just don't think it should be used when LC is available. ULAN is relatively comprehensive for the sort of art you get in encycopaedic museums or art museums, but is not terribly useful for most archives. ULAN definitely does not conform to AACR2. See "Jefferson, Thomas (American statesman, architect, and draftsman, 1743-1826)" as the preferred heading.

I can make the box wider, but if you click on the heading, the full heading will appear underneath with a link to the VIAF record. Is that good enough?
