### ISSUE TITLE
dc:format only harvest valid mime-types

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#51]
Only harvest valid mime-types (IMT) from the source OAI dc:format. Ignore all other values in the source dc:format.

Map valid mime-types to the reference edm:WebResource.
If format is edited in the harvester, replace existing mime-types in source dc:format with the new format value.

Thumbnail edm:WebResource's dc:format value should always be image/jpeg.

@jallibunn

**Comment by ewg118** [comment]
I have tightened the validation not only to look for valid mime-types in dc:format, but valid DCMI types in dc:type and dc:rights statements. In doing so, I had to make changes to the code so that the user can continue in the submission of the set for harvesting when having selected the relevant drop-down menu in the remediation section.

In this scenario, a user can submit a set in step 1, skip the radio buttons on the remediation page, and see a list of record errors for missing mime-types on the validation page. The user can go back to the remediation page, select a mime type, return to the validation page, and then click "Contribute" to submit the set (assuming no other errors). Note that from the validation page, if a user returns back to the remediation page, deselects a mime type, and then goes back to validation, the errors will re-appear, blocking contribution of the set.

**Comment by adehner** [comment]
It seems like editing format in the harvester has NO effect in the following cases:
- the source OAI dc:format already contains a mime type
- the mime type can be programmatically derived from the reference webresource

So editing dc:format in the harvester only adds a mime-type to records that are missing a mime-type and for which a mime-type cannot be derived. Is this accurate?

If format is edited in the harvester but the reference webresource does not display in validation results, is the chosen dc:format value applied to webresource?

Sorry if I'm mucking this up. It seems like there are some behind the scenes conditionals, and I'm not sure what they are.

**Comment by adehner** [comment]
Since format isn't required, presence of format doesn't need to be validated. Please remove it from the validated fields.

**Comment by ewg118** [comment]
I noticed that the format from the harvester drop down menu was not being applied to Oregon Digital or Omeka sets. This is fixed now. Format is no longer validated as a requirement for submission of a set, but it is still outputted in the validation page, if available.
