### ISSUE TITLE
Issues with check.xpl

### ISSUE THREAD

**Issue by cwyant-alliance** [Orbis-Cascade-Alliance/harvester#65]
When uploading a finding aid with digital objects to Archives West, the uploader passes a URL to the Harvester at /admin/check before ingest. An example request from Archives West:
https://harvester.orbiscascade.org/admin/check?sets=http://content.libraries.wsu.edu/oai/oai.php?verb=ListRecords&metadataPrefix=oai_dc&set=matsura&repository=waps

results in an error: The request includes illegal arguments, repeated arguments, or is missing required arguments. "metadataPrefix"

Disabling the check allows finding aids to upload correctly and associated digital objects are ingested correctly.

Please update check.xpl or advise how I should change the URL parameters to provide a positive result.

**Comment by ewg118** [comment]
I think that the issue here is that the `sets` request parameter isn't being encoded for a URL. I did make a minor modification to the web service, changing `sets` to `set`, since the service only reads one OAI-PMH set URL to be as efficient as possible (it didn't appear that a finding aid would ever be connected to more than one OAI-PMH set)
