### ISSUE TITLE
Imports for UW, WWU, Boise State successful but do not display in Admin

### ISSUE THREAD

**Issue by cwyant-alliance** [Orbis-Cascade-Alliance/harvester#68]
I re-uploaded all Archives West finding aids with digital objects, which triggered an ingest of the associated sets. Digital objects from WSU, Willamette, and others import fine. But digital objects for WSU, University of Washington, and Boise State appear to import correctly, but, as far as I can tell, are not being associated with an institution or and ARK ID.

For example:
UW: http://archiveswest.orbiscascade.org/ark:/80444/xv10269
Boise State: http://archiveswest.orbiscascade.org/ark:/80444/xv61544

The Archives West XSLT uses /apis/count to display the link under digital objects and, as you can see, it successfully returns a value for these finding aids. However, clicking the link to the full display (which uses /apis/get) returns an error of "no associated ARK".

Also, these sets do not appear on the Harvester Admin page. If these were not successfully uploaded, why does the count API return a value? And how do I delete the items if they do not appear on the Admin page?

**Comment by ewg118** [comment]
This was a tricky one to track down. The CHOs did harvest correctly, but I found 5 or 6 repository RDF files that still used http://nwda.orbiscascade.org instead of http://archiveswest.orbiscascade.org as the URI for the repository. Thus, when harvesting, there was no connection between <http://archiveswest.orbiscascade.org/contact#idbb> as defined as the edm:dataProvider in the ore:Aggregation generated by the harvest process and the repository name, home page, etc. triples associated with the incorrect URI of <http://nwda.orbiscascade.org/contact#idbb> which was in the old version of the repository RDF.

I changed these URLs and committed the changes to Github. I then refreshed the repository RDF in the Harvester admin, and everything is fixed. The thumbnails now display in http://archiveswest.orbiscascade.org/ark:/80444/xv61544

**Comment by ewg118** [comment]
For University of Washington, Special Collections, my documentation states that the MARC code is wau-ar, not wauar. So the wrong code is being communicated in the agency URI

**Comment by cwyant-alliance** [comment]
Hi Ethan, the MARC code for UW should be "wauar". Thank you for your help
on this.

Curtis Wyant
IT Manager
Orbis Cascade Alliance
cwyant@orbiscascade.org
541-246-2470 x 203

**Comment by ewg118** [comment]
I changed wau-ar to wauar in the harvester config file and in the repository RDF. I refreshed the repository metadata in the triplestore, and http://archiveswest.orbiscascade.org/ark:/80444/xv10269 now shows thumbnails correctly.
