### ISSUE TITLE
AAT URIs in Primo OAI

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#71]
I'm still seeing AAT URIs in OAI records for Primo. I believe these are a result of remediation in the harvester, rather than enrichment. We would like to test Primo normalization rules against the production OAI as soon as next week, but we need the Primo OAI to be accurate before that process can begin.

As of today, the URIs are visible in the following collections:
Storyteller Photographs (Linfield)
Oregon State University Commencement Programs (OSU)
Linn County Postcard Collection (Lewis & Clark College)
Japanese Postcard Collection (Lewis & Clark College)
The Academician (George Fox)

@jallibunn

**Comment by ewg118** [comment]
This is done, but note that you'll have to re-harvest these sets so that the skos:Concepts get generated on ingestion. I tested a set on my computer and the AAT term is coming through in the Primo OAI-PMH, and the skos:Concept is in the endpoint.

**Comment by jallibunn** [comment]
Ethan, you need to explain how to re-harvest sets on which remediation was done in the harvester. We can't really ask our institutions to do work over again--what are the other options?
@ewg118 @adehner

**Comment by ewg118** [comment]
There are no other options. We are still essentially in a testing phase,
sorting out the last of the transformation problems. It isn't possible to
implement a "reload" button because there's always a potential that a set
that was previously valid may have been changed in some way to no longer be
valid (removing a date, for example). Therefore, the system always needs to
go through the validation phase.
