### ISSUE TITLE
Start and end dates of date ranges

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#74]
Date transformations in the harvester specifications include the following:
_If the date value is a date span (two 8601 compliant dates separated by a forward slash “/”), map the first date to start properties and the last date to end properties in Primo and DPLA._

According to the specs, a date range (eg. 1901/1910) would be transformed for Primo like this:
<dc:date>1901/1910</dc:date>
<dc:date.start>19010101</dc:date.start>
<dc:date.end>19101231</dc:date.end>

The harvester is completing this transformation inconsistently. Successfully for several sets. But not successfully for the Gifford Photographic Collection from OSU:
<img width="889" alt="screen shot 2017-06-01 at 4 31 56 pm" src="https://cloud.githubusercontent.com/assets/6174191/26704985/deca202e-46e7-11e7-8af8-2deda825d733.png">

@jallibunn

**Comment by ewg118** [comment]
According to the date parsing conditional I had written, the dc:date would be parsed by looking first for multiple values concatenated with ';', then ranges with '/', then year ranges with '-', and then default to a single date value. As it turns out, Oregon Digital can have multiple date values, like '1935/1945; 2013-06-28', and so there was never any secondary parsing beyond extracting out the '1935/1945'. I have restructured the conditional to split on ';' when applicable, and then parse the date. Therefore, 1935/1945 will now come through as a date range. I think there are very few cases where this actually occurs, which is why we haven't discovered it until now.
