### ISSUE TITLE
Primo OAI is down

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#78]
The Primo OAI set request returns an Orbeon error instead of records:
http://harvester.orbiscascade.org/oai-pmh/?verb=ListRecords&set=primo&metadataPrefix=oai_dc

I noticed this a few hours ago, around the time the Academician set was contributed. A few minutes ago I noticed that the Academician set was listed twice, with 2 different metadataPrefixes. I deleted the set with metadataPrefix=dcs and this action deleted both sets. The Academician set may not be related to the OAI problem, but I mention it because they happened around the same time, I observed weirdness with both, and I remember that a contributed set broke the OAI once before.

@jallibunn

**Comment by ewg118** [comment]
I modified the OAI XSLT to only render the timestamp for the first prov:generatedAtTime. There should only ever be one of these, but ingesting the same exact set with two possible metadata prefixes (thus two URIs) is potentially a big problem. Since the set (a dcmitype:Collection) URI is different, it does not remove the old ore:Aggregations or CHOs related to the set before ingesting the new set, which means that the triples for the ore:Aggregations and CHOs will merge together. Thus, the ore:Aggregation will end up having two different timestamps for ingestion date, and the CHOs will have two dcterms:isPartOf links to two different set URIs.
