### ISSUE TITLE
Re-submitting sets to the harvester

### ISSUE THREAD

**Issue by jallibunn** [Orbis-Cascade-Alliance/harvester#86]
Naturally, no sooner do we get submissions to the harvester only to hear that our members want to know how to deal with a set that has additions to it. I will need to write documentation for this since our existing documentation does not address this; before I do I’d like to check my assumptions with you to ensure that they are correct. 

Scenario: Institution A has submitted a set with 105 objects for both DPLA and Primo to the harvester. They have subsequently added objects to the set; it now contains 135 objects. They need to re-submit the set to the harvester. 

First assumption: Including the other 20 objects requires action; the harvester doesn’t “know” about additions to the set. (I know—obvious—but checking for clarity)

Second: The institution does or does not need to delete the version already in the harvester (indicate which one in your reply)

Third: If they do not, the harvester will recognize the objects already in--so in this case it will know to only add 20 objects. (indicate yes or no in your reply)

Fourth: If so, they will or will not overwrite the existing objects—whether they remediate or enrich (indicate will/will not in your reply)

If I can get your answers on these questions I will write up the documentation and run it by you for confirmation. I’ve gotten this question three times already this week, so need to get it done in the next week. 

@cwyant-alliance

**Comment by ewg118** [comment]
Hi Jodi,

1. Correct, the harvester doesn't know. It is not possible to set up a
recurring ingest for a set because of action that may need to be taken
during the validation phase.
2. The institution does not need to remove the set before re-ingesting.
Removal of CHOs occurs as part of the underlying workflow before creating
new CHOs from the OAI-PMH
3. The harvester adds all objects from the set after purging what was
already there. I understand that it would be more efficient to use the
OAI-PMH date range to harvest objects changed since the last harvest date,
but it's really not worth implementing these changes since there are only a
handful of sets with more than a few thousand CHOs. It's pointless to
harvest the most recent changes from a set of 100 objects.
4. Existing objects are effectively overwritten since they are deleted
before replaced. Enriched items are still enriched because of the lookups
that were previously established on the last harvest. Remediation is likely
to be required again, regardless of overwriting, because the 20 new items
might need languages, rights statements, etc.

Ethan

**Comment by jallibunn** [comment]
Great, thank you for your reply. 

I'll write up the documentation and run it by you, just to make sure it's all right. 

J
@cwyant-alliance

**Comment by jallibunn** [comment]
Here's a draft for your quick review: https://docs.google.com/a/orbiscascade.org/document/d/1tz_8jC1sJRxJb859ODUBd5f1yY84HeXVxHOFCkbfVsY/edit?usp=sharing

@cwyant-alliance

**Comment by ewg118** [comment]
This looks good.

**Comment by jallibunn** [comment]
Thanks, Ethan!
