### ISSUE TITLE
questions on ontologies

### ISSUE THREAD

**Issue by VladimirAlexiev** [Orbis-Cascade-Alliance/harvester#89]
See the query at #88.  It includes the following terms:
- https://github.com/Orbis-Cascade-Alliance/nwda-editor#visitation.
  Naming an ontology by an editor that uses it is a very bad idea. Map to existing terms as much as possible (in this case I believe EAG would have an appropriate term). Furthermore, that URL does not return any ontology. 
- http://purl.org/archival/vocab/arch#Archive: that URL redirects to http://gslis.simmons.edu/archival/arch#Archive, which does not respond

**Comment by ewg118** [comment]
I had to make up a property because there was nothing relevant at the time (2014). Between that and the arch ontology (which was maintained in 2014), there's little action to be taken until Records in Contexts is published or the archival community adopts the schema.org archival extension overseen by Richard Wallis. The repository metadata were never originally intended to be publicly available, and so I invented several properties that don't resolve or belong to a formal ontology
